### ISSUE TITLE
Support Django 1.8 or higher

### ISSUE THREAD

**Issue by gEndelf** [arneb/django-campaign#6]
When I try to use this package - exception raised:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ghost/.virtualenvs/demo-pack/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/ghost/.virtualenvs/demo-pack/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/ghost/.virtualenvs/demo-pack/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ghost/.virtualenvs/demo-pack/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/ghost/.virtualenvs/demo-pack/local/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ghost/.virtualenvs/demo-pack/local/lib/python2.7/site-packages/campaign/models.py", line 9, in <module>
    from campaign.fields import JSONField
  File "/home/ghost/.virtualenvs/demo-pack/local/lib/python2.7/site-packages/campaign/fields.py", line 4, in <module>
    from django.utils import simplejson
ImportError: cannot import name simplejson
```

django.utils.simplejson was removed in Django 1.5
Instead of own JsonField implementation - django-extensions can be used.

**Comment by gEndelf** [comment]
@arneb it seems this issue was fixed long time ago, but when I try to install django-campaign -version 0.2.0 used with broken requirements

plz update pip package version
thx

**Comment by silentjay** [comment]
What's the latest version of Django that this will work with? Falls over all over the place on 1.9

**Comment by bashu** [comment]
+1 for 0.3.0 release

**Comment by bashu** [comment]
@gEndelf see #8

**Comment by bashu** [comment]
if someone interested here is another fork https://github.com/bashu/fluentcms-campaign

**Comment by arneb** [comment]
0.3.0 is now released and should work with Django 1.8. 
Support for 1.9 (currently not tested) will follow shortly.
