### ISSUE TITLE
Cannot send campaign from Django Admin

### ISSUE THREAD

**Issue by HenryMehta** [arneb/django-campaign#15]
It may be I've installed django-campaign incorrectly but when setting up a simple first example and trying to send it from django admin module I get the error` invalid literal for int() with base 10: '2/change'` which I think is because the default admin view expects everything after the app/model to be the integer value of the primary key.

**Comment by arneb** [comment]
Thank you for the report. I think you are using Django 1.9+, right? There was a change in Admin URL structure and the /change/ URL was introduced. I will have a look into it and fix campaign.

**Comment by HenryMehta** [comment]
That's right, I'm using 1.9.  I therefore presume this is new. Will it 
work if I set it programmaitcally?


Henry

**Comment by arneb** [comment]
Until it is fixed just open the Campaign object in django admin and replace "change" with "send" in the Browser address bar. The url should look like this:

http://127.0.0.1:8000/admin/campaign/campaign/1/send/

The problem is this link:
https://github.com/arneb/django-campaign/blob/master/campaign/templates/admin/campaign/campaign/change_form.html#L8
which only works up to Django 1.8. It needs to be changed into an absolute url (will do this soon).

**Comment by HenryMehta** [comment]
That gives me the following error:
`'WSGIRequest' object has no attribute 'REQUEST'`

**Comment by arneb** [comment]
ok, then please wait a bit until I've tested it with Django 1.9 myself ...

**Comment by HenryMehta** [comment]
/var/www/cltc/env/lib/python2.7/site-packages/campaign/admin.py in send_view
            'is_popup': request.REQUEST.has_key('_popup'), 

request.REQUEST needs replacing with request.POST or request.GET

**Comment by arneb** [comment]
Current master branch should now work with Django 1.9! 
If you find any more problems please re-open this ticket or create a new one.

(Django 1.10 support and a new release on PyPI will follow in the next days/weeks)

**Comment by HenryMehta** [comment]
I've tried uninstall and the install and I continue to get the same errors.  New version isn't being downloaded

**Comment by arneb** [comment]
Uninstall and then install directly from the git repository, e.g.

pip install git+https://github.com/arneb/django-campaign.git@master#egg=django-campaign --upgrade

**Comment by HenryMehta** [comment]
Thank you
